name: CI/CD for Node.js API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Scan for Vulnerabilities
        run: npm audit

      - name: Build the Application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        run: |
           ssh guardianes.del.zodiaco@grupo6.com "cd /path/to/app && git pull origin main && npm install && pm2 restart all"
          echo "Deploying..."
